Mark exception-raising functions as diverging
This allows, for example, raising in a match arm without the need to return a dummy value. The following compiles when VM::raise diverges:

    fn serialize() -> RString {
        // ...

        match stylesheet.to_css() {
            Ok(output) => RString::new_utf8(&output.code),
            Err(_) => VM::raise(Class::from_existing("StandardError"), "failed to generate CSS")
        }
    }

Without these changes, the above fails to compile:

    error[E0308]: `match` arms have incompatible types
       --> src/stylesheet.rs:103:23
        |
    101 | /         match stylesheet.to_css() {
    102 | |             Ok(output) => RString::new_utf8(&output.code),
        | |                           ------------------------------- this is found to be of type `rutie::RString`
    103 | |             Err(_) => VM::raise(Class::from_existing("StandardError"), "failed to generate CSS")
        | |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `rutie::RString`, found `()`
    104 | |         }
        | |_________- `match` arms have incompatible types